# Regression Preparation

In [890]:
import os
import pandas as pd
import numpy as np

os.chdir('/Users/janlinzner/Projects/Master-Thesis-Spatial-Proximity-Venture-Capital')

In [891]:
data = pd.read_csv('data/sets-for-r/companies_seed.csv')

In [892]:
unique_countries = data['Headquarters Country'].unique()
print(unique_countries)

['United Kingdom' 'Germany' 'France' 'Finland' 'Austria' 'Latvia' 'Norway'
 'Belgium' 'Denmark' 'Ireland' 'Spain' 'The Netherlands' 'Portugal'
 'Switzerland' 'Hungary' 'Estonia' 'Czech Republic' 'Italy' 'Greece'
 'Lithuania' 'Slovakia (Slovak Republic)' 'Poland']

In [893]:
selected_vars = [
    "Company ID",
    "Organization Name", 
    "Founded Year", 
    "First Seed Year",
    "Organization Name URL",
    "Austria", 
    "Belgium", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France", 
    "Germany", 
    "Greece", 
    "Hungary", 
    "Ireland", 
    "Italy", 
    "Latvia", 
    "Lithuania", 
    "Norway", 
    "Poland", 
    "Portugal", 
    "Slovakia (Slovak Republic)", 
    "Spain", 
    "Switzerland", 
    "The Netherlands", 
    "United Kingdom",
    "Headquarters Country",
    "Success",
    "Exit Binary",
    "Funding Success",
    "Years to Exit",
    "Min Seed Investor Distance",
    "Number of Founders",
    "Hub Binary",
    "Distance to Hub",
    "B2B Binary",
    "Startups Within 50km",
    "VCs Within 50km",
    "Share Successful Startups in Environment",
    "Top University Count",
    "Top University Ecosystem Binary", 
    "Number Seed Rounds",
    "Avg Seed Investor Distance",
    "Avg Seed Investor Pairwise Distance",
    "Average Seed Investors Portfolio Organizations",
    "Number Seed Investors",
    "Regional Seed Investor Binary",
    "Overregional Seed Investor Binary",
    "Avg Age of Seed Investors",
    "Avg Exits of Seed Investors",
    "Specific VC in Seed Binary",
    "Target VC in Seed Binary",
    "Hub VC in Seed Binary",
    "Accelerator Funding Binary",
    "Angel Group Funding Binary",
    "Micro VC Funding Binary",
    "Corporate Venture Capital Funding Binary",
    "Homecountry Investor in Seed Binary",
    "Seed Investor Same City",
    "Seed Lead Investor Same City",
    "Years to Seed",
    "Total Seed Funding (M)",
    "Energy",
    "Materials",
    "Industrials",
    "Consumer Discretionary",
    "Consumer Staples",
    "Health Care",
    "Financials",
    "Information Technology",
    "Communication Services",
    "Utilities",
    "Real Estate",
    "Other",
    "Last Equity Funding Type",
    "Latitude",
    "Longitude",
    "Number Lead Seed Investors",
    "Regional Lead Seed Investor Binary",
    "Overregional Lead Seed Investor Binary",
    "Specific Lead VC in Seed Binary",
    "Target Lead VC in Seed Binary",
    "Accelerator Lead Funding Binary",
    "Angel Group Lead Funding Binary",
    "Micro VC Lead Funding Binary",
    "Corporate Venture Capital Lead Funding Binary",
    "Number Seed Investors Same City",
    "Number Seed Lead Investors Same City",
    "Seed Lead Investor Same City",
    "Number Homecountry Investors",
    "Number Homecountry Lead Investors",
    "Homecountry Lead Investor",
    "Hub Lead VC in Seed Binary",
    "VCs Within 50km",
    "Top University Count",
    "Top University Ecosystem Binary",
    "Founded Startups in Environment",
    "Successful Startups in Environment",
    "Share Successful Startups in Environment",
    "Minimum Seed VC Distance - Non Lead",
    "Avg Seed VC Distance - Non Lead",
    "Maximum Seed VC Distance - Non Lead",
    "Minimum Lead Seed VC Distance",
    "Avg Lead Seed VC Distance",
    "Maximum Lead Seed VC Distance",
    "Min Seed Investor Pairwise Distance",
    "Max Seed Investor Pairwise Distance",
    "GDP Growth (%) in Funding Year",
    "Investment Volume in First Seed Year (log)",
    "Exit Date",
    "Max Seed Investor Distance"
]

data = data[selected_vars]

In [894]:
countries = [
    "Austria", "Belgium", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary",
    "Ireland", "Italy", "Latvia", "Lithuania", "Norway", "Poland", "Portugal", "Slovakia (Slovak Republic)", "Spain",
    "Switzerland", "The Netherlands", "United Kingdom"
]

country_counts = data[countries].sum().reset_index()
country_counts.columns = ['Country', 'Number of Companies']

In [895]:
valid_countries = country_counts[country_counts['Number of Companies'] >= 0]['Country'].tolist()

data = data[data[valid_countries].any(axis=1)]

In [896]:
columns_to_drop = [col for col in countries if col not in valid_countries]
data = data.drop(columns=columns_to_drop)

In [897]:
data = data.dropna(subset=['Number of Founders'])

In [898]:
data['Hub Binary'] = data['Hub Binary'].astype(bool)

Age

In [899]:
data['Age'] = data['First Seed Year'] - data['Founded Year']

In [900]:
data['Age'] = data['Age'].apply(lambda x: max(x, 0))

In [901]:
selected_vars_1 = [
    "Company ID",
    "Organization Name", 
    "Founded Year", 
    "Organization Name URL",
    "Headquarters Country",
    "Number of Founders",
    "Age",
    "Hub Binary",
    "B2B Binary",
    "Number Seed Rounds",
    "Avg Seed Investor Distance",
    "Avg Seed Investor Pairwise Distance",
    "Average Seed Investors Portfolio Organizations",
    "Number Seed Investors",
    "Avg Age of Seed Investors",
    "Specific VC in Seed Binary",
    "Target VC in Seed Binary",
    "Hub VC in Seed Binary",
    "Accelerator Funding Binary",
    "Angel Group Funding Binary",
    "Micro VC Funding Binary",
    "Corporate Venture Capital Funding Binary",
    "Homecountry Investor in Seed Binary",
    "Seed Investor Same City",
    "Seed Lead Investor Same City",
    "Total Seed Funding (M)",
    "Energy",
    "Materials",
    "Industrials",
    "Consumer Discretionary",
    "Consumer Staples",
    "Health Care",
    "Financials",
    "Information Technology",
    "Communication Services",
    "Utilities",
    "Real Estate",
    "Other",
    "Success",
    "Exit Binary",
    "Funding Success",
    "Years to Exit",
    "Last Equity Funding Type",
    "Latitude",
    "Longitude",
    "Regional Seed Investor Binary",
    "Overregional Seed Investor Binary",
    "Min Seed Investor Distance",
    "Number Lead Seed Investors",
    "Years to Seed",
    "Regional Lead Seed Investor Binary",
    "Overregional Seed Investor Binary",
    "Overregional Lead Seed Investor Binary",
    "Avg Exits of Seed Investors",
    "Specific Lead VC in Seed Binary",
    "Target Lead VC in Seed Binary",
    "Accelerator Lead Funding Binary",
    "Angel Group Lead Funding Binary",
    "Micro VC Lead Funding Binary",
    "Corporate Venture Capital Lead Funding Binary",
    "Number Seed Investors Same City",
    "Number Seed Lead Investors Same City",
    "Seed Lead Investor Same City",
    "Number Homecountry Investors",
    "Number Homecountry Lead Investors",
    "Homecountry Lead Investor",
    "Hub Lead VC in Seed Binary",
    "VCs Within 50km",
    "Top University Ecosystem Binary",
    "Top University Count",
    "Founded Startups in Environment",
    "Successful Startups in Environment",
    "Share Successful Startups in Environment",
    "Distance to Hub",
    "Minimum Seed VC Distance - Non Lead",
    "Avg Seed VC Distance - Non Lead",
    "Maximum Seed VC Distance - Non Lead",
    "Minimum Lead Seed VC Distance",
    "Avg Lead Seed VC Distance",
    "Maximum Lead Seed VC Distance",
    "Min Seed Investor Pairwise Distance",
    "Max Seed Investor Pairwise Distance",
    "GDP Growth (%) in Funding Year",
    "Investment Volume in First Seed Year (log)",
    "Exit Date",
    "Max Seed Investor Distance"
]

data = data[selected_vars_1]

Network

In [902]:
company_counts_per_country = data['Headquarters Country'].value_counts()
print(company_counts_per_country)

Headquarters Country
United Kingdom                3298
Germany                       1532
France                        1003
Spain                          743
The Netherlands                482
Italy                          405
Finland                        324
Poland                         317
Switzerland                    291
Denmark                        278
Ireland                        242
Hungary                        201
Belgium                        201
Portugal                       186
Austria                        152
Estonia                        150
Norway                         116
Czech Republic                 103
Lithuania                       89
Latvia                          61
Greece                          58
Slovakia (Slovak Republic)      38
Name: count, dtype: int64

In [903]:
seed_help = pd.read_csv('data/sets-for-r/seed_help.csv')

In [904]:
seed_help = seed_help[seed_help['Company ID'].isin(data['Company ID'])]

In [905]:
selected_vars_final = [
'Company ID', 
'Organization Name', 
'Founded Year',
'Headquarters Country',
'Organization Name URL',
'Number of Founders', 
'Age',
'Hub Binary',
'B2B Binary',
'Total Seed Funding (M)', 
'Number Seed Rounds', 
'Number Seed Investors',
'Avg Seed Investor Distance',
'Avg Seed Investor Pairwise Distance',
'Average Seed Investors Portfolio Organizations',
'Avg Age of Seed Investors',
"Regional Seed Investor Binary",
"Overregional Seed Investor Binary",
'Specific VC in Seed Binary', 
'Target VC in Seed Binary',
'Hub VC in Seed Binary', 
'Accelerator Funding Binary',
'Angel Group Funding Binary', 
'Micro VC Funding Binary',
'Corporate Venture Capital Funding Binary',
'Homecountry Investor in Seed Binary', 
'Seed Investor Same City',
'Seed Lead Investor Same City',
'Energy', 
'Materials', 
'Industrials',
'Consumer Discretionary', 
'Consumer Staples', 
'Health Care',
'Financials', 
'Information Technology', 
'Communication Services',
'Utilities', 
'Real Estate', 
'Other', 
'Success', 
'Exit Binary',
'Funding Success',
'Years to Exit',
'Min Seed Investor Distance',
'Last Equity Funding Type',
'Latitude',
'Longitude',
"Number Lead Seed Investors",
"Regional Seed Investor Binary",
"Regional Lead Seed Investor Binary", 
"Years to Seed",
"Overregional Seed Investor Binary",
"Overregional Lead Seed Investor Binary",
"Avg Exits of Seed Investors",
"Specific Lead VC in Seed Binary",
"Target Lead VC in Seed Binary",
"Accelerator Lead Funding Binary",
"Angel Group Lead Funding Binary",
"Micro VC Lead Funding Binary",
"Corporate Venture Capital Lead Funding Binary",
"Number Seed Investors Same City",
"Number Seed Lead Investors Same City",
"Seed Lead Investor Same City",
"Number Homecountry Investors",
"Number Homecountry Lead Investors",
"Homecountry Lead Investor",
"Hub Lead VC in Seed Binary",
"VCs Within 50km",
'Top University Count',
"Top University Ecosystem Binary",
'Founded Startups in Environment',
"Successful Startups in Environment",
'Share Successful Startups in Environment',
'Distance to Hub',
"Minimum Seed VC Distance - Non Lead",
"Avg Seed VC Distance - Non Lead",
"Maximum Seed VC Distance - Non Lead",
"Minimum Lead Seed VC Distance",
"Avg Lead Seed VC Distance",
"Maximum Lead Seed VC Distance",
"Min Seed Investor Pairwise Distance",
"Max Seed Investor Pairwise Distance",
'GDP Growth (%) in Funding Year',
"Investment Volume in First Seed Year (log)",
"Exit Date",
"Max Seed Investor Distance"
]

final_order = [
'Company ID', 
'Organization Name', 
'Organization Name URL',
'Founded Year',
'Headquarters Country',
'Latitude',
'Longitude', 
'Number of Founders', 
'Age',
'Hub Binary',
'B2B Binary', 
'Total Seed Funding (M)', 
'Number Seed Rounds', 
'Number Seed Investors',
'Avg Seed Investor Distance',
'Min Seed Investor Distance',
'Avg Seed Investor Pairwise Distance',
'Average Seed Investors Portfolio Organizations',
'Avg Age of Seed Investors',
'Specific VC in Seed Binary', 
'Target VC in Seed Binary',
'Hub VC in Seed Binary', 
'Accelerator Funding Binary',
'Angel Group Funding Binary', 
'Micro VC Funding Binary',
'Corporate Venture Capital Funding Binary',
'Homecountry Investor in Seed Binary', 
'Seed Investor Same City',
'Seed Lead Investor Same City',
'Energy', 
'Materials', 
'Industrials',
'Consumer Discretionary', 
'Consumer Staples', 
'Health Care',
'Financials', 
'Information Technology', 
'Communication Services',
'Utilities', 
'Real Estate', 
'Other', 
'Success', 
'Exit Binary',
'Funding Success',
'Years to Exit',
'Last Equity Funding Type',
"Number Lead Seed Investors",
"Years to Seed",
"Regional Seed Investor Binary",
"Regional Lead Seed Investor Binary",
"Overregional Seed Investor Binary",
"Overregional Lead Seed Investor Binary",
"Avg Exits of Seed Investors",
"Specific Lead VC in Seed Binary",
"Target Lead VC in Seed Binary",
"Accelerator Lead Funding Binary",
"Angel Group Lead Funding Binary",
"Micro VC Lead Funding Binary",
"Corporate Venture Capital Lead Funding Binary",
"Number Seed Investors Same City",
"Number Seed Lead Investors Same City",
"Seed Lead Investor Same City",
"Number Homecountry Investors",
"Number Homecountry Lead Investors",
"Homecountry Lead Investor",
"Hub Lead VC in Seed Binary",
"VCs Within 50km",
'Top University Count',
'Top University Ecosystem Binary',
'Founded Startups in Environment',
'Successful Startups in Environment',
'Share Successful Startups in Environment',
'Distance to Hub',
"Minimum Seed VC Distance - Non Lead",
"Avg Seed VC Distance - Non Lead",
"Maximum Seed VC Distance - Non Lead",
"Minimum Lead Seed VC Distance",
"Avg Lead Seed VC Distance",
"Maximum Lead Seed VC Distance",
"Min Seed Investor Pairwise Distance",
"Max Seed Investor Pairwise Distance",
"GDP Growth (%) in Funding Year",
"Investment Volume in First Seed Year (log)",
"Exit Date",
"Max Seed Investor Distance"
]

In [906]:
data = data[selected_vars_final]

In [907]:
data = data[final_order]

In [908]:
data.rename(columns={
    "Company ID": "company_id",
    "Organization Name": "organization_name",
    "Organization Name URL": "organization_name_url",
    "Founded Year": "founded_year",
    "Headquarters Country": "headquarters_country",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Number of Founders": "number_of_founders",
    "Age": "age",
    "Regional Seed Investor Binary": "regional_seed_investor_binary",
    "Overregional Seed Investor Binary": "overregional_seed_investor_binary",
    "Hub Binary": "hub_binary",
    "B2B Binary": "b2b_binary",
    "Total Seed Funding (M)": "total_seed_funding_m",
    "Number Seed Rounds": "number_seed_rounds",
    "Number Seed Investors": "number_seed_investors",
    "Avg Seed Investor Distance": "avg_seed_investor_distance",
    "Min Seed Investor Distance": "minimum_seed_vc_distance",
    "Avg Seed Investor Pairwise Distance": "avg_seed_investor_pairwise_distance",
    "Average Seed Investors Portfolio Organizations": "average_seed_investors_portfolio_organizations",
    "Avg Age of Seed Investors": "avg_age_of_seed_investors",
    "Specific VC in Seed Binary": "specific_vc_in_seed_binary",
    "Target VC in Seed Binary": "target_vc_in_seed_binary",
    "Hub VC in Seed Binary": "hub_vc_in_seed_binary",
    "Accelerator Funding Binary": "accelerator_funding_binary",
    "Angel Group Funding Binary": "angel_group_funding_binary",
    "Micro VC Funding Binary": "micro_vc_funding_binary",
    "Corporate Venture Capital Funding Binary": "corporate_vc_funding_binary",
    "Homecountry Investor in Seed Binary": "homecountry_investor_in_seed_binary",
    "Seed Investor Same City": "seed_investor_same_city",
    "Seed Lead Investor Same City": "seed_lead_investor_same_city",
    "Energy": "energy",
    "Materials": "materials",
    "Industrials": "industrials",
    "Consumer Discretionary": "consumer_discretionary",
    "Consumer Staples": "consumer_staples",
    "Health Care": "health_care",
    "Financials": "financials",
    "Information Technology": "information_technology",
    "Communication Services": "communication_services",
    "Utilities": "utilities",
    "Real Estate": "real_estate",
    "Other": "other",
    "Success": "success",
    "Exit Binary": "exit_binary",
    "Funding Success": "funding_success",
    "Years to Exit": "years_to_exit",
    "Last Equity Funding Type": "last_equity_funding_type",
    "Number Lead Seed Investors": "number_lead_seed_investors",
    "Years to Seed": "years_to_seed",
    "Regional Seed Investor Binary": "regional_seed_investor_binary",
    "Regional Lead Seed Investor Binary": "regional_lead_seed_investor_binary",
    "Overregional Seed Investor Binary": "overregional_seed_investor_binary",
    "Overregional Lead Seed Investor Binary": "overregional_lead_seed_investor_binary",
    "Avg Exits of Seed Investors": "avg_exits_of_seed_investors",
    "Specific Lead VC in Seed Binary": "specific_lead_vc_in_seed_binary",
    "Target Lead VC in Seed Binary": "target_lead_vc_in_seed_binary",
    "Accelerator Lead Funding Binary": "accelerator_lead_funding_binary",
    "Angel Group Lead Funding Binary": "angel_group_lead_funding_binary",
    "Micro VC Lead Funding Binary": "micro_vc_lead_funding_binary",
    "Corporate Venture Capital Lead Funding Binary": "corporate_vc_lead_funding_binary",
    "Number Seed Investors Same City": "number_seed_investors_same_city",
    "Number Seed Lead Investors Same City": "number_seed_lead_investors_same_city",
    "Seed Lead Investor Same City": "seed_lead_investor_same_city",
    "Number Homecountry Investors": "number_homecountry_investors",
    "Number Homecountry Lead Investors": "number_homecountry_lead_investors",
    "Homecountry Lead Investor": "homecountry_lead_investor",
    "Hub Lead VC in Seed Binary": "hub_lead_vc_in_seed_binary",
    "VCs Within 50km": "vcs_within_50km",
    "Top University Count": "top_university_count",
    "Top University Ecosystem Binary": "top_university_ecosystem_binary",
    "Founded Startups in Environment": "founded_startups_in_environment",
    "Successful Startups in Environment": "successful_startups_in_environment",
    "Share Successful Startups in Environment": "share_successful_startups_in_environment",
    "Distance to Hub": "distance_to_hub",
    "Minimum Seed VC Distance - Non Lead": "minimum_seed_vc_distance_non_lead",
    "Avg Seed VC Distance - Non Lead": "avg_seed_vc_distance_non_lead",
    "Maximum Seed VC Distance - Non Lead": "maximum_seed_vc_distance_non_lead",
    "Minimum Lead Seed VC Distance": "minimum_lead_seed_vc_distance",
    "Maximum Lead Seed VC Distance": "maximum_lead_seed_vc_distance",
    "Avg Lead Seed VC Distance": "avg_lead_seed_vc_distance",
    "Min Seed Investor Pairwise Distance": "min_seed_investor_pairwise_distance",
    "Max Seed Investor Pairwise Distance": "max_seed_investor_pairwise_distance",
    "GDP Growth (%) in Funding Year": "gdp_growth_founding_year",
    "Investment Volume in First Seed Year (log)": "investment_volume_first_seed_year",
    "Exit Date": "exit_date",
    "Max Seed Investor Distance": "max_seed_investor_distance"
}, inplace=True)

Same Country

In [909]:
seed_help

,Round ID,Company ID,Organization Name,Organization Name URL,Organization Founded Year,Investor ID,Investor Name,Investor URL,Investor Founded Date,Investor Longitude,...,Seed Lead Investor Same City,Country,Headquarters Country,Homecountry Investor,Homecountry Lead Investor,Seed Investor Within 50km,Seed Lead Investor Within 50km,Investor Distance to Hub,Hub_VC_Flag,Hub_Lead_VC_Flag
2,2,126,INKsearch.co,https://www.crunchbase.com/organization/inksea...,2019,248,EKIPA Investments,https://www.crunchbase.com/organization/ekipa-...,2019-01-01,19.936856,...,False,Poland,Poland,True,False,False,False,252.563928,False,False
3,2,126,INKsearch.co,https://www.crunchbase.com/organization/inksea...,2019,11,Startup Wise Guys,https://www.crunchbase.com/organization/startu...,2012-01-01,24.745369,...,False,Estonia,Poland,False,False,False,False,0.000000,True,False
14,11,33,Plenti,https://www.crunchbase.com/organization/plenti...,2018,223,NCBR Investment Fund ASI S.A.,https://www.crunchbase.com/organization/ncbr-i...,NaN,-86.950845,...,False,United States,Poland,False,False,False,False,6032.012739,False,False
15,11,33,Plenti,https://www.crunchbase.com/organization/plenti...,2018,208,4growth VC,https://www.crunchbase.com/organization/4growt...,NaN,21.006725,...,True,Poland,Poland,True,True,True,True,0.000000,True,True
16,11,33,Plenti,https://www.crunchbase.com/organization/plenti...,2018,148,AIP Seed,https://www.crunchbase.com/organization/aip-seed,2009-01-01,21.006725,...,False,Poland,Poland,True,False,True,False,0.000000,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48656,71148,21838,Intale,https://www.crunchbase.com/organization/intale,2013,3703,PJ Tech Catalyst,https://www.crunchbase.com/organization/pj-tec...,2012-01-01,23.734832,...,False,Greece,Greece,True,False,True,False,1283.894358,False,False
48659,71153,21888,ISTMOS,https://www.crunchbase.com/organization/istmos,2015,1981,Sente Ventures,https://www.crunchbase.com/organization/sente-...,2008-01-01,-87.624421,...,False,United States,Greece,False,False,False,False,5889.598932,False,False
48660,71161,21857,Funkmartini,https://www.crunchbase.com/organization/funkma...,2013,1029,VentureFriends,https://www.crunchbase.com/organization/ventur...,2016-01-01,23.734832,...,False,Greece,Greece,True,False,True,False,1283.894358,False,False
48661,71165,21868,ParkAround,https://www.crunchbase.com/organization/park-a...,2013,311,Rockstart,https://www.crunchbase.com/organization/rockst...,2011-07-01,4.892453,...,False,The Netherlands,Greece,False,False,False,False,0.000000,True,False
48662,71168,21868,ParkAround,https://www.crunchbase.com/organization/park-a...,2013,3703,PJ Tech Catalyst,https://www.crunchbase.com/organization/pj-tec...,2012-01-01,23.734832,...,False,Greece,Greece,True,False,True,False,1283.894358,False,False

All Investors from the same country

In [910]:
# Create a new variable to check if all investors in the seed phase are from the same country
seed_help['seed_investors_all_same_country'] = seed_help.groupby('Company ID')['Country'].transform(lambda x: x.nunique() == 1)

# Map this variable to the main dataset
data['seed_investors_all_same_country'] = data['company_id'].map(seed_help.groupby('Company ID')['seed_investors_all_same_country'].first())

All Investors from the same country as investee

In [911]:
# Create a new variable to check if all investors in the seed phase are from the same country as the startup
seed_help['seed_investors_all_same_country_as_startup'] = seed_help.apply(
    lambda row: row['Country'] == row['Headquarters Country'], axis=1
)

# Group by 'Company ID' and check if all investors for a company are from the same country as the startup
seed_help['seed_investors_all_same_country_as_startup'] = seed_help.groupby('Company ID')['seed_investors_all_same_country_as_startup'].transform(all)

# Map this variable to the main dataset
data['seed_investors_all_same_country_as_startup'] = data['company_id'].map(
    seed_help.groupby('Company ID')['seed_investors_all_same_country_as_startup'].first()
)

Same City

In [912]:
# Create a new variable to check if all investors in the seed phase are from the same city
seed_help['seed_investors_all_same_city'] = seed_help.groupby('Company ID')['Seed Investor Same City'].transform(lambda x: x.all())

# Map this variable to the main dataset
data['seed_investors_all_same_city'] = data['company_id'].map(seed_help.groupby('Company ID')['seed_investors_all_same_city'].first())

Existing Funding

In [913]:
# data = data[data['total_seed_funding_m'] > 0]
# print("Rows with total_seed_funding_m > 0 retained. Updated dataset size:", len(data))

Load the rounds dataset

In [914]:
rounds = pd.read_csv('data/sets-for-r/rounds.csv')

Earliest and Latest Seed Round Data

In [915]:
seed_help['Announced Date'] = pd.to_datetime(seed_help['Announced Date'])

seed_round_dates = seed_help.groupby('Company ID')['Announced Date'].agg(['min', 'max']).reset_index()
seed_round_dates.rename(columns={'min': 'earliest_seed_round_date', 'max': 'latest_seed_round_date'}, inplace=True)

data.rename(columns={'company_id': 'Company ID'}, inplace=True)

data = data.merge(seed_round_dates, on='Company ID', how='left')

European investors

In [916]:
european_countries = [
    "Austria", "Belgium", "Bulgaria", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary","Iceland",
    "Ireland", "Italy", "Latvia", "Lithuania", "Liechtenstein", "Luxembourg", "Norway", "Poland", "Portugal", "Romania", "Slovenia",  "Slovakia (Slovak Republic)", "Spain",
    "Sweden", "Switzerland", "The Netherlands","Ukraine", "United Kingdom"
]

# Create the 'european_investor' variable: True if at least one investor is European
seed_help['european_investor'] = seed_help['Country'].isin(european_countries)

# Create the 'all_european_investor' variable: True if all investors are European
seed_help['all_european_investor'] = seed_help.groupby('Company ID')['Country'].transform(lambda x: x.isin(european_countries).all())

# Map these variables to the main dataset
data['european_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['european_investor'].any())
data['all_european_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['all_european_investor'].first())

Global Investor

In [917]:
# Create the 'global_investor' variable: True if at least one investor is not European
seed_help['global_investor'] = ~seed_help['Country'].isin(european_countries)

# Create the 'all_global_investor' variable: True if all investors are not European
seed_help['all_global_investor'] = seed_help.groupby('Company ID')['Country'].transform(lambda x: ~x.isin(european_countries).all())

# Map these variables to the main dataset
data['global_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['global_investor'].any())
data['all_global_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['all_global_investor'].first())

US investor

In [918]:
# Create the 'us_investor' variable: True if at least one investor is from the United States
seed_help['us_investor'] = seed_help['Country'] == 'United States'

# Create the 'all_us_investor' variable: True if all investors are from the United States
seed_help['all_us_investor'] = seed_help.groupby('Company ID')['Country'].transform(lambda x: (x == 'United States').all())

# Map these variables to the main dataset
data['us_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['us_investor'].any())
data['all_us_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['all_us_investor'].first())

DACH Investors

In [919]:
dach_countries = [
    "Austria", "Germany", "Switzerland"
]

seed_help['dach_investor'] = seed_help['Country'].isin(dach_countries)

seed_help['all_dach_investor'] = seed_help.groupby('Company ID')['Country'].transform(lambda x: x.isin(dach_countries).all())

data['dach_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['dach_investor'].any())
data['all_dach_investor'] = data['Company ID'].map(seed_help.groupby('Company ID')['all_dach_investor'].first())

Save Set

In [920]:
data.to_csv('data/sets-for-r/data_global.csv', index=False)
data_global = data.copy()

All Homecountry Investors

In [921]:
seed_help['all_homecountry_investors_in_seed_binary'] = seed_help.groupby('Company ID')['Homecountry Investor'].transform(all)


data_global['all_homecountry_investors_in_seed_binary'] = data_global['Company ID'].map(
    seed_help.groupby('Company ID')['all_homecountry_investors_in_seed_binary'].first()
)

Rename ID

In [922]:
data_global.rename(columns={
    "Company ID": "company_id",
    
}, inplace=True)

Order

In [923]:
desired_order = [
    'company_id', 'organization_name', 'organization_name_url', 'headquarters_country', 
    'latitude', 'longitude', 'founded_year', 'number_of_founders', 'b2b_binary', 'hub_binary',
    'energy', 'materials', 'industrials', 'consumer_discretionary', 'consumer_staples', 'health_care',
    'financials', 'information_technology', 'communication_services', 'utilities', 'real_estate', 'other', 'age',
    'number_seed_rounds', 'number_seed_investors', 'number_lead_seed_investors', 'total_seed_funding_m', 
    'earliest_seed_round_date', 'latest_seed_round_date', 'last_equity_funding_type', 'average_seed_investors_portfolio_organizations', 
    'regional_seed_investor_binary', 'regional_lead_seed_investor_binary', 'overregional_seed_investor_binary', 
    'overregional_lead_seed_investor_binary', 'avg_age_of_seed_investors', 'avg_exits_of_seed_investors', 'specific_vc_in_seed_binary', 
    'specific_lead_vc_in_seed_binary', 'target_vc_in_seed_binary', 'target_lead_vc_in_seed_binary', 'accelerator_funding_binary', 
    'accelerator_lead_funding_binary', 'angel_group_funding_binary', 'angel_group_lead_funding_binary','micro_vc_funding_binary',
    'micro_vc_lead_funding_binary', 'corporate_vc_funding_binary', 'corporate_vc_lead_funding_binary', 'number_seed_investors_same_city',
    'number_seed_lead_investors_same_city', 'seed_investor_same_city', 'seed_lead_investor_same_city', 'seed_investors_all_same_city', 'number_homecountry_investors',
    'number_homecountry_lead_investors', 'homecountry_investor_in_seed_binary', 'homecountry_lead_investor', 'all_homecountry_investors_in_seed_binary', 'hub_vc_in_seed_binary', 
    'hub_lead_vc_in_seed_binary', 'global_investor',
    'all_global_investor', 'us_investor', 'all_us_investor', 'dach_investor', 'all_dach_investor', 'european_investor', 'all_european_investor',
    'vcs_within_50km', 'top_university_count', 'top_university_ecosystem_binary', 'founded_startups_in_environment', 'successful_startups_in_environment', 
    'share_successful_startups_in_environment', 'distance_to_hub', 'avg_seed_investor_distance', 'minimum_seed_vc_distance', 'max_seed_investor_distance', 
    'minimum_seed_vc_distance_non_lead', 'avg_seed_vc_distance_non_lead', 'maximum_seed_vc_distance_non_lead', 'minimum_lead_seed_vc_distance', 
    'avg_lead_seed_vc_distance', 'maximum_lead_seed_vc_distance', 'avg_seed_investor_pairwise_distance', 'min_seed_investor_pairwise_distance', 
    'max_seed_investor_pairwise_distance', 'gdp_growth_founding_year',
    'investment_volume_first_seed_year', 'exit_binary', 'funding_success', 'success', 'exit_date', 'years_to_exit'
]

data_global = data_global[desired_order]

In [924]:
desired_order = list(dict.fromkeys(desired_order))

data_global = data_global[desired_order]

In [925]:
data_global = data_global.loc[:, ~data_global.columns.duplicated()]

In [926]:
data_global['number_lead_seed_investors'].fillna(0, inplace=True)

/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/248020188.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_global['number_lead_seed_investors'].fillna(0, inplace=True)

In [927]:
unique_last_equity_funding_types = data_global['last_equity_funding_type'].unique()
print(unique_last_equity_funding_types)

['Seed' 'Series A' 'Venture - Series Unknown' 'Series B' 'Post-IPO Equity'
 'Private Equity' 'Series C' 'Angel' 'Series E' 'Series D' 'Pre-Seed'
 'Corporate Round' 'Equity Crowdfunding' 'Series F' 'Undisclosed'
 'Series G' 'Initial Coin Offering' 'Series I']

Additional Success

In [928]:
post_seed_funding_types = ['Series A', 'Series B', 'Venture - Series Unknown', 'Private Equity',
 'Series C', 'Corporate Round', 'Series D', 'Series E', 'Series F', 'Series G', 'Series I']

data_global['post_seed_funding'] = data_global['last_equity_funding_type'].isin(post_seed_funding_types)

data_global['post_seed_funding'] = data_global['last_equity_funding_type'].isin(post_seed_funding_types)

columns = data_global.columns.tolist()
funding_success_index = columns.index('funding_success')
columns.insert(funding_success_index + 1, columns.pop(columns.index('post_seed_funding')))
data_global = data_global[columns]

Rename Success

In [929]:
data_global.rename(columns={'success': 'exit_funding_success'}, inplace=True)

In [930]:
data_global['exit_round_success'] = data_global['exit_binary'] | data_global['post_seed_funding']

In [931]:
columns = data_global.columns.tolist()
exit_funding_success_index = columns.index('exit_funding_success')
columns.insert(exit_funding_success_index + 1, columns.pop(columns.index('exit_round_success')))
data_global = data_global[columns]

More Thresholds for Same City / Regional

In [932]:
seed_help.rename(columns={"Company ID": "company_id"}, inplace=True)

In [933]:
thresholds = [20, 30, 40, 50, 70, 100]

for threshold in thresholds:
    investor_column_name = f'seed_investor_same_city_{threshold}'
    lead_investor_column_name = f'seed_lead_investor_same_city_{threshold}'
    num_investors_column_name = f'number_seed_investors_same_city_{threshold}'
    num_lead_investors_column_name = f'number_seed_lead_investors_same_city_{threshold}'

    seed_help[investor_column_name] = seed_help['Distance km'] < threshold

    seed_help[lead_investor_column_name] = seed_help['Lead'] & seed_help[investor_column_name]

    num_investors_within_threshold = seed_help.groupby('company_id')[investor_column_name].sum()
    num_lead_investors_within_threshold = seed_help.groupby('company_id')[lead_investor_column_name].sum()

    data_global[num_investors_column_name] = data_global['company_id'].map(num_investors_within_threshold)
    data_global[num_lead_investors_column_name] = data_global['company_id'].map(num_lead_investors_within_threshold)

    data_global[investor_column_name] = data_global[num_investors_column_name] > 0
    data_global[lead_investor_column_name] = data_global[num_lead_investors_column_name] > 0

In [934]:
for threshold in thresholds:
    investor_column_name = f'seed_investor_same_city_{threshold}'
    lead_investor_column_name = f'seed_lead_investor_same_city_{threshold}'

    seed_investor_same_city_index = data_global.columns.tolist().index('seed_investors_all_same_city')

    columns = data_global.columns.tolist()
    columns.insert(seed_investor_same_city_index + 1, columns.pop(columns.index(investor_column_name)))
    columns.insert(seed_investor_same_city_index + 2, columns.pop(columns.index(lead_investor_column_name)))

    data_global = data_global[columns]

Year of First Round

In [935]:
data_global['year_first_round'] = data_global['earliest_seed_round_date'].dt.year

columns = data_global.columns.tolist()
last_equity_funding_type_index = columns.index('last_equity_funding_type')
columns.insert(last_equity_funding_type_index + 1, columns.pop(columns.index('year_first_round')))
data_global = data_global[columns]

In [936]:
data_global

,company_id,organization_name,organization_name_url,headquarters_country,latitude,longitude,founded_year,number_of_founders,b2b_binary,hub_binary,...,number_seed_investors_same_city_30,number_seed_lead_investors_same_city_30,number_seed_investors_same_city_40,number_seed_lead_investors_same_city_40,number_seed_investors_same_city_50,number_seed_lead_investors_same_city_50,number_seed_investors_same_city_70,number_seed_lead_investors_same_city_70,number_seed_investors_same_city_100,number_seed_lead_investors_same_city_100
0,16452,Traffic Observation via Management,https://www.crunchbase.com/organization/traffi...,United Kingdom,53.407199,-2.991680,2007,1.0,True,False,...,1,0,1,0,1,0,1,0,1,0
1,9341,Secusmart,https://www.crunchbase.com/organization/secusmart,Germany,51.225402,6.776314,2007,1.0,True,False,...,0,0,0,0,0,0,0,0,0,0
2,1893,Adipsys,https://www.crunchbase.com/organization/adipsys,France,43.641141,7.008625,2007,1.0,True,False,...,0,0,0,0,0,0,0,0,0,0
3,16174,Crescendo Biologics,https://www.crunchbase.com/organization/cresce...,United Kingdom,52.205531,0.118664,2007,1.0,True,True,...,2,0,2,0,2,0,2,0,3,0
4,1894,ActiveEon,https://www.crunchbase.com/organization/activeeon,France,43.619523,7.051816,2007,1.0,True,False,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10265,18186,FLOWBIO,https://www.crunchbase.com/organization/flow-bio,United Kingdom,51.489334,-0.144055,2020,2.0,False,True,...,2,0,2,0,2,0,2,0,2,0
10266,18183,Yoof Agency,https://www.crunchbase.com/organization/yoof-a...,United Kingdom,51.489334,-0.144055,2020,1.0,False,True,...,0,0,0,0,0,0,0,0,0,0
10267,18182,Noah,https://www.crunchbase.com/organization/noah-7ab8,United Kingdom,51.489334,-0.144055,2020,1.0,True,True,...,0,0,0,0,0,0,0,0,0,0
10268,19011,Hackrate,https://www.crunchbase.com/organization/hackrate,Hungary,47.497879,19.040238,2020,2.0,True,False,...,4,3,4,3,4,3,4,3,4,3
10269,8389,DIDIT,https://www.crunchbase.com/organization/didit-...,Germany,52.510885,13.398937,2020,2.0,False,True,...,4,2,4,2,4,2,4,2,4,2

Success

In [937]:
# Create a new 'success' column based on the conditions
data_global['success'] = data_global['exit_funding_success'] | data_global['exit_round_success']

# Reorder the columns to place 'success' after 'exit_round_success'
columns = data_global.columns.tolist()
exit_round_success_index = columns.index('exit_round_success')
columns.insert(exit_round_success_index + 1, columns.pop(columns.index('success')))
data_global = data_global[columns]

In [938]:
columns = data_global.columns.tolist()
exit_round_success_index = columns.index('exit_round_success')
columns.insert(exit_round_success_index + 1, columns.pop(columns.index('success')))
data_global = data_global[columns]

Log transform share of successful startups

In [939]:
data_global['log_share_successful_startups_in_environment'] = np.log1p(data_global['share_successful_startups_in_environment'])

columns = data_global.columns.tolist()
share_successful_startups_index = columns.index('share_successful_startups_in_environment')
columns.insert(share_successful_startups_index + 1, columns.pop(columns.index('log_share_successful_startups_in_environment')))
data_global = data_global[columns]

In [940]:
data_global['log_share_successful_startups_in_environment'] = np.log1p(data_global['share_successful_startups_in_environment'])

Lead Variables change to missing

In [941]:
mask = (data_global['regional_lead_seed_investor_binary'] == False) & (data_global['overregional_lead_seed_investor_binary'] == False)
data_global.loc[mask, ['regional_lead_seed_investor_binary', 'overregional_lead_seed_investor_binary']] = np.nan

columns_to_update = [
    'regional_lead_seed_investor_binary', 'overregional_lead_seed_investor_binary',
    'specific_lead_vc_in_seed_binary', 'target_lead_vc_in_seed_binary', 
    'accelerator_lead_funding_binary',
    'angel_group_lead_funding_binary', 'micro_vc_lead_funding_binary', 
    'corporate_vc_lead_funding_binary', 
     'seed_lead_investor_same_city', 
     'seed_lead_investor_same_city_100', 
    'seed_lead_investor_same_city_70',  
    'seed_lead_investor_same_city_50', 'seed_lead_investor_same_city_40', 
    'seed_lead_investor_same_city_30', 
    'seed_lead_investor_same_city_20', 'number_homecountry_lead_investors', 
     'homecountry_lead_investor',
     'hub_lead_vc_in_seed_binary'
]

data_global.loc[mask, columns_to_update] = np.nan

/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, ['regional_lead_seed_investor_binary', 'overregional_lead_seed_investor_binary']] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, ['regional_lead_seed_investor_binary', 'overregional_lead_seed_investor_binary']] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan
/var/folders/n8/ynbdx9r10lv6l8yh1m_hmbsh0000gn/T/ipykernel_8676/369145622.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_global.loc[mask, columns_to_update] = np.nan

In [942]:
data_global.to_csv('data/sets-for-r/data.csv', index=False)